# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ariSeuE44YmNqLKUf0GjyOi0wHfSgAE4
"""

import streamlit as st
import pdfplumber
import pytesseract
from pdf2image import convert_from_path
from PIL import Image
import re
import pandas as pd
import tempfile
import os

# Set tesseract path only if needed (Windows users)
# pytesseract.pytesseract.tesseract_cmd = r"/usr/bin/tesseract"

st.set_page_config(page_title="PDF Data Extraction Bot", layout="centered")
st.title("🤖 Extract Data from PDF Bills & Receipts (Free Forever)")

uploaded_file = st.file_uploader("📄 Upload a PDF file", type="pdf")

def extract_text(file_path):
    text = ''
    try:
        with pdfplumber.open(file_path) as pdf:
            for page in pdf.pages:
                text += page.extract_text() or ''
    except:
        images = convert_from_path(file_path)
        for img in images:
            text += pytesseract.image_to_string(img)
    return text

def extract_fields(text):
    mobile = re.search(r'\b(\d{10})\b', text)
    amount = re.search(r'Amount Paid\s*=?\s*\₹?\$?([0-9,.]+)', text, re.IGNORECASE)
    date = re.search(r'Date and Time\s*([0-9]{1,2}\s+\w+,\s*\d{4})', text, re.IGNORECASE)
    time = re.search(r'at\s*([0-9]{1,2}:[0-9]{2}\s*[apAP][mM])', text)
    order_id = re.search(r'Order ID\s*[:\-]?\s*(\w+)', text, re.IGNORECASE)
    status = re.search(r'Payment Status\s*(\w+)', text, re.IGNORECASE)

    return {
        "Mobile Number": mobile.group(1) if mobile else "Not Found",
        "Amount Paid": amount.group(1) if amount else "Not Found",
        "Date": date.group(1) if date else "Not Found",
        "Time": time.group(1) if time else "Not Found",
        "Order ID": order_id.group(1) if order_id else "Not Found",
        "Payment Status": status.group(1) if status else "Not Found"
    }

if uploaded_file:
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
        tmp_file.write(uploaded_file.read())
        tmp_path = tmp_file.name

    with st.spinner("Extracting data..."):
        text = extract_text(tmp_path)
        fields = extract_fields(text)
        df = pd.DataFrame([fields])

    st.subheader("📋 Extracted Data")
    st.table(df)

    st.download_button("⬇️ Download CSV", df.to_csv(index=False), "extracted_data.csv")

    st.markdown("---")
    st.caption("Built with ❤️ Streamlit & Python | Free Forever")